# Generated by Django 6.0.1 on 2026-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(help_text='Введите содержание заметки', max_length=10000, verbose_name='Текст заметки'),
        ),
    ]
